akvelon/falco-website

config/_default/config.toml
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> test commit

docker-compose.yaml, layouts/index.en.html, layouts/partials/head.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> added netlify

assets/scss/_nav.scss, assets/scss/_variables.scss, layouts/partials/navbar-lang-selector.html, layouts/partials/navbar.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> navbar redesign

assets/js/anchor.js
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix: fix headers acnhor issue

assets/scss/_nav.scss
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> header shadow

assets/scss/_nav.scss, layouts/partials/navbar-lang-selector.html, layouts/partials/navbar.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> Landing navigation

assets/scss/_base.scss, assets/scss/_variables.scss
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> feature: section tag class

layouts/index.en.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> moved community section

data/en/community.yaml, layouts/index.en.html, layouts/partials/community.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> added community links

assets/scss/_base.scss, config/_default/params.toml, i18n/en/en.yaml, layouts/partials/logos.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> change end-users to also-used-by

assets/scss/_base.scss, layouts/index.en.html, layouts/partials/logos.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix: change header styles, delete negative margin

assets/scss/_base.scss, layouts/index.en.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix: added try falco button to features section

assets/scss/_landing.scss
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix: features icon shadow

assets/scss/_styles_project.scss, assets/scss/_variables.scss, assets/scss/mixins/_grid.scss, layouts/partials/community.html, layouts/partials/logos.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> Landing grid

assets/scss/_base.scss, assets/scss/_landing.scss, config/_default/config.toml, layouts/partials/footer.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> update footer styles and layout

assets/scss/_landing.scss, assets/scss/_nav.scss, data/en/community.yaml, layouts/index.en.html, layouts/partials/community.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> Landing schema

assets/scss/_base.scss, assets/scss/_landing.scss, layouts/partials/footer.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix: change styles

layouts/index.en.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix: removed cncf link

assets/scss/_landing.scss, layouts/partials/community.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix: paddings

content/en/about/_index.md, layouts/about/about.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> add about page

assets/scss/_base.scss, assets/scss/_landing.scss, i18n/en/en.yaml, layouts/partials/footer.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> feat: change footer styles

assets/js/announcement-bar.js, assets/scss/_nav.scss, layouts/_default/baseof.html, layouts/partials/navbar.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> feat: navbar animation

layouts/_default/baseof.html, layouts/docs/baseof.html, layouts/partials/scripts.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix: added announcement bar to blog and docs

assets/scss/_base.scss, assets/scss/_buttons.scss, assets/scss/_landing.scss, assets/scss/_main-container.scss, assets/scss/_variables.scss, i18n/en/en.yaml, layouts/index.en.html, layouts/partials/features.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> Landing features

layouts/partials/footer.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix: change footer sstyles from grid to col

layouts/partials/footer.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix: delete footer link

assets/scss/_base.scss, assets/scss/_variables.scss, i18n/en/en.yaml, layouts/index.en.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> feat: featured section

layouts/index.en.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix: change sections order

config/_default/config.toml, content/en/about/_index.md, layouts/about/baseof.html, layouts/partials/navbar.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> feat: add dropdown about menu item

assets/scss/_styles_project.scss, assets/scss/_variables_restyle.scss, assets/scss/main_restyle.scss, assets/scss/mixins/_grid.scss
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> feat: cards and designs import

assets/scss/_cards.scss, assets/scss/_variables_project.scss, assets/scss/_variables_restyle.scss, assets/scss/main_restyle.scss, content/en/about/faq.md, layouts/shortcodes/card_faq.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> feat: added faq cards

assets/scss/_variables_restyle.scss, assets/scss/main_restyle.scss, layouts/shortcodes/card.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> feat: controllable card

content/en/training/_index.md
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix: delete test text

content/en/about/falco.md
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> feat: add cards to falco.md

assets/scss/_variables_restyle.scss, assets/scss/main_restyle.scss, content/en/about/falco.md, layouts/about/baseof.html, layouts/shortcodes/about/tab.html, layouts/shortcodes/about/tabs.html, layouts/shortcodes/blocks/content.html, layouts/shortcodes/card.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> feat: fixed about section home page styles

assets/scss/main_restyle.scss, content/en/about/falco.md, content/en/about/faq.md
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> feat: faq page restyle

content/en/about/falco.md, layouts/shortcodes/two_column_block_img.html
…mobile
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> fix:  two_column shortcode to correct mobiles layout

assets/scss/_card.scss, layouts/partials/section-index.html
> /kind bug
/kind design
/kind user-interface
> /area blog
> /area videos
`section-index` links component in `docs` section redesign
Fixes #
=> feat: section-index links redesign

assets/scss/_blog.scss, assets/scss/_variables_project.scss, i18n/en/en.yaml, layouts/blog/content.html
> /kind bug
> /kind design
> /area blog
> /area videos
Fixes #
=> Feat: blog
